# Generated by Django 4.0.1 on 2022-02-08 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_bids_buyer_remove_list_user_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='date',
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 8, 19, 44, 10, 827813)),
        ),
    ]
