# Generated by Django 4.0.1 on 2022-02-08 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_product_date_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 8, 20, 26, 38, 37446)),
        ),
    ]
