# Generated by Django 4.0.1 on 2022-02-08 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 8, 20, 29, 57, 334649)),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
