# Generated by Django 4.0.1 on 2022-02-11 04:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_watchlist_remove_list_item_list_category_list_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 4, 33, 16, 885120, tzinfo=utc)),
        ),
    ]
