# Generated by Django 4.0.1 on 2022-02-11 07:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_watchlist_user_alter_bids_id_alter_list_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 7, 1, 41, 894314, tzinfo=utc)),
        ),
    ]
