# Generated by Django 4.0.1 on 2022-02-11 10:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
from decimal import Decimal

class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 10, 57, 45, 886833, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='list',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=32),
        ),
    ]
