# Generated by Django 4.0.1 on 2022-02-11 11:42

import datetime
from decimal import Decimal
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 11, 42, 52, 580604, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='list',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=32),
        ),
    ]
