# Generated by Django 4.0.1 on 2022-02-12 12:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_bids_bidder_alter_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 12, 12, 23, 49, 280632, tzinfo=utc)),
        ),
    ]
