# Generated by Django 4.0.1 on 2022-02-13 10:53

import datetime
from decimal import Decimal
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_alter_list_date_bids'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListDump',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lister', models.CharField(default=None, max_length=64)),
                ('prodtitle', models.CharField(blank=True, max_length=128, null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=32)),
                ('category', models.TextField(default=None, max_length=72)),
            ],
        ),
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 10, 53, 0, 102461, tzinfo=utc)),
        ),
    ]
