# Generated by Django 4.0.1 on 2022-02-14 05:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_listdump_winner_alter_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 5, 41, 24, 296547, tzinfo=utc)),
        ),
    ]
