# Generated by Django 4.0.1 on 2022-02-14 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_list_description_alter_list_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='bidder',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='item',
        ),
        migrations.DeleteModel(
            name='ListDump',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='item',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bids',
        ),
        migrations.DeleteModel(
            name='List',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
