# Generated by Django 4.0.1 on 2022-02-14 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_alter_list_date_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
