# Generated by Django 4.0.1 on 2022-02-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commenter',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
